### 상영관에 좌석 리스트 등록
POST localhost:8081/api/v1/seats/new
Content-Type: application/json

{
  "hallId": "1",
  "rows": "2",
  "columns": "3"
}

### 좌석 리스트 조회
GET localhost:8081/api/v1/seats?screeningId=1&hallId=1